### ISSUE TITLE
Pomelo?

### ISSUE THREAD

**Issue by justinclift** [gwenn/lemon-rs#1]
Just stumbled on this `lemon-rs` repo while looking through some of your other (Go) SQLite code again. :wink:

At the bottom of the Readme, there's a mention of [lemon_rust](https://github.com/rodrigorc/lemon_rust).

As a data point, the author of lemon_rust seems to have created a 2nd implementation, called Pomelo:

&nbsp; &nbsp; https://github.com/rodrigorc/pomelo

Not sure if it's a useful source of idea, but mentioning just in case. :smile:

**Comment by gwenn** [comment]
I already knew but thanks.
I may be wrong but:
* all changes in original `lemon` C sources are not backported in `pomelo`.
* there is no evidence that original SQLite C parser can be implemented with `pomelo`.

But the proc_macro approach is a clever idea.

**Comment by justinclift** [comment]
No worries.  Only mentioned it because of your linking to the authors previous project.  Wasn't sure if you'd seen the new one too. :smile:
