### ISSUE TITLE
Would this be suitable for writing a SQLite language server

### ISSUE THREAD

**Issue by bbkane** [gwenn/lemon-rs#14]
Looks super neat!

**Comment by gwenn** [comment]
The main issue is #10.
You should also take a look at [nom-sql](https://github.com/ms705/nom-sql) and [sqlparser-rs](https://github.com/ballista-compute/sqlparser-rs).
And I guess that for a language server, you need to recover / continue on error. But if this [feature](https://github.com/gwenn/lemon-rs/blob/master/Cargo.toml#L21) is deactivated by default.

**Comment by bbkane** [comment]
Thanks!!
