### ISSUE TITLE
Consider separating SQL parsing from lemon implementation

### ISSUE THREAD

**Issue by thomcc** [gwenn/lemon-rs#2]
As a passive onlooker: It's a bit strange that this project happens to contain both the lemon implementation and the SQLite-compatible SQL syntax parser in the same crate.

I feel like it might be cleaner if you separated these, so that someone who just wanted to use lemon without using it to parse SQL wouldn't have to bring that in.

Alternatively, just doing it as a feature would avoid that too (although I think it makes more sense to have lemon and SQL parsing separated).

Splitting would also fix this issue I think, since these would just be features on the generated parser/lexer: https://github.com/gwenn/lemon-rs/blob/master/Cargo.toml#L20

**Comment by thomcc** [comment]
Humm, nevermind, I see why this isn't the case. I misunderstood the purpose of this repo.

**Comment by gwenn** [comment]
See [pomelo](https://github.com/gwenn/lemon-rs/issues/1#issuecomment-630950376).
