### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MarinPostma** [gwenn/lemon-rs#22]
Hey @gwenn,

would it be possible to cut a release from main? We'd like to publish on crates.io, but then we rely on the upstream patch 😇 

Have a nice day

**Comment by MarinPostma** [comment]
@gwenn thanks!

**Comment by gwenn** [comment]
https://github.com/gwenn/lemon-rs/releases/tag/v0.6.0
https://crates.io/crates/sqlite3-parser
