### ISSUE TITLE
Crash on invalid UTF-8

### ISSUE THREAD

**Issue by MarinPostma** [gwenn/lemon-rs#45]
The following input crashes the parser because of an invalid UTF8 sequence
[bad-utf8.txt](https://github.com/gwenn/lemon-rs/files/14605850/bad-utf8.txt)

**Comment by gwenn** [comment]
I cannot reproduce:
```sh
lemon-rs % cargo run --example sql_cmds bad-utf8.txt
bad-utf8.txt
CREATE TABLE LEC� (ABLEBL "0", "0" EATE TABL0BL REFERENCES a);
CREATE TABLE LEC� (ASE0F�Y0);
Err: unknown table option: TA at (3, 30) in /Users/gwen/Downloads/bad-utf8.txt
```
I guess that the crash was related to #44 which is fixed.
